### ISSUE TITLE
Room's file listing

### ISSUE THREAD

**Issue by indrakaw** [Szero/volaupload.sh#6]
This topic might out of current features. Is there a way to listing file on a room in Volafile.io?

e.g.
```
volalisting.sh -r SomeRoom | wget -i -
```
This will download via `wget` input listing file. `volalisting.sh` is a script that generated links to download file. Typical JavaScript pre-rendered link as-seen-on-web-browser.

**Comment by szero** [comment]
That's out of the scope of this project. You can use that python script i sent you on discord for that. I could download the static page and parse out the links from it but its not very good method since RealDolos made APIs for vola. I'm planning on making vola desktop client with download support that would work like old DownThemAll addon for Firefox, but haven't started working on it yet.

**Comment by szero** [comment]
In meantime, you can use this CLI script for downloading: https://gist.github.com/Szero/59c6bb98f5b7807de1a49e3c79db5b3c
